/* =========================================================
   lyrics.js v2 — Multi-artist lyrics
   
   Cách sử dụng:
   - Key: "assets/artists/[artist-id]/audio/[filename].mp3"
   - Value: lời bài hát (text hoặc HTML)
   - Để trống nếu chưa có lời
   
   User sẽ điền lời sau khi có file mp3 thực tế
   ========================================================= */

const LYRICS = {
  "assets/artists/bray/audio/1 - Man Down ft Ếch và Báo.mp3": ``,
  "assets/artists/bray/audio/10 - Vùng An Toàn ft V#.mp3": ``,
  "assets/artists/bray/audio/11 - The One ft Đạt G.mp3": ``,
  "assets/artists/bray/audio/12 - Ghệ Mới ft Young H.mp3": ``,
  "assets/artists/bray/audio/13 - Y Chang Em (interlude).mp3": ``,
  "assets/artists/bray/audio/14 - Feel At Home.mp3": ``,
  "assets/artists/bray/audio/15 - Còn Ai Ngoài Anh Với Em.mp3": ``,
  "assets/artists/bray/audio/16 - Viết Em Bản Tình Ca.mp3": ``,
  "assets/artists/bray/audio/17 - B.S.N.L ft YoungH.mp3": ``,
  "assets/artists/bray/audio/18 - B.S.N.L 2 ft YoungH.mp3": ``,
  "assets/artists/bray/audio/19 - B.S.N.L 3 ft YoungH.mp3": ``,
  "assets/artists/bray/audio/2 - Tệ Hại & Xấu Xí (Intro).mp3": ``,
  "assets/artists/bray/audio/20 - Để Ai Cần ft Young H.mp3": ``,
  "assets/artists/bray/audio/3 - Đúng Như Lời Họ Nói.mp3": ``,
  "assets/artists/bray/audio/4 - Cho Con (Lullaby pt.2).mp3": ``,
  "assets/artists/bray/audio/5 - Felina.mp3": ``,
  "assets/artists/bray/audio/6 - Ta CÓ Nên (Intro).mp3": ``,
  "assets/artists/bray/audio/7 - Cho Ba.mp3": ``,
  "assets/artists/bray/audio/8 - Chân Mệnh ft B Rizzle.mp3": ``,
  "assets/artists/bray/audio/9 - Một Vòng Sài Gòn.mp3": ``,
  "assets/artists/dangrangto/audio/1 - xương rồng.mp3": ``,
  "assets/artists/dangrangto/audio/10 - đánh rơi.mp3": ``,
  "assets/artists/dangrangto/audio/11 - quenvaonhau.mp3": ``,
  "assets/artists/dangrangto/audio/12 - món quà.mp3": ``,
  "assets/artists/dangrangto/audio/13 - đắm say trong tình yêu.mp3": ``,
  "assets/artists/dangrangto/audio/14 - hãy đến đây bên anh trong một chiều mùa thu.mp3": ``,
  "assets/artists/dangrangto/audio/15 - để dành cho em.mp3": ``,
  "assets/artists/dangrangto/audio/16 - thế giới của anh.mp3": ``,
  "assets/artists/dangrangto/audio/17 - MOIEM.mp3": ``,
  "assets/artists/dangrangto/audio/2 - My lil bitch ft TeuYungBoy.mp3": ``,
  "assets/artists/dangrangto/audio/3 - cây màu đen ft MR LANH, LWKI.mp3": ``,
  "assets/artists/dangrangto/audio/4 - buổi sáng Khương Đình ft BIG WIND.mp3": ``,
  "assets/artists/dangrangto/audio/5 - vùng vẫy ft ZEXZEX.mp3": ``,
  "assets/artists/dangrangto/audio/6 - baby anh đợi có lâu.mp3": ``,
  "assets/artists/dangrangto/audio/7 - bolero buồn.mp3": ``,
  "assets/artists/dangrangto/audio/8 - tốt cho anh.mp3": ``,
  "assets/artists/dangrangto/audio/9 - một ly.mp3": ``,
  "assets/artists/hieuthuhai/audio/1 - Anh Nên Đi Khỏi Đây.mp3": ``,
  "assets/artists/hieuthuhai/audio/10 - Dạo Gần Đây Anh Thấy Anh Không Bằng Ai Hết.mp3": ``,
  "assets/artists/hieuthuhai/audio/11 - Chờ Tới Khi Anh Về ft Hoàng Tôn.mp3": ``,
  "assets/artists/hieuthuhai/audio/12 - Ai Cũng Phải Bắt Đầu Từ Đâu Đó.mp3": ``,
  "assets/artists/hieuthuhai/audio/13 - Giờ Thì Ai Cười.mp3": ``,
  "assets/artists/hieuthuhai/audio/14 - 237°C ft LOWNA.mp3": ``,
  "assets/artists/hieuthuhai/audio/15 - Không Phải Gu ft. B Ray & Tage.mp3": ``,
  "assets/artists/hieuthuhai/audio/16 - Siêu Sao.mp3": ``,
  "assets/artists/hieuthuhai/audio/17 - Đi Họp Lớp.mp3": ``,
  "assets/artists/hieuthuhai/audio/18 - Không Thể Say.mp3": ``,
  "assets/artists/hieuthuhai/audio/19 - Exit Sign ft. marzuz.mp3": ``,
  "assets/artists/hieuthuhai/audio/2 - Hết Yêu.mp3": ``,
  "assets/artists/hieuthuhai/audio/20 - Sắp Nổi Tiếng.mp3": ``,
  "assets/artists/hieuthuhai/audio/21 - Everything Will Be Okay.mp3": ``,
  "assets/artists/hieuthuhai/audio/22 - Cho Em An Toàn.mp3": ``,
  "assets/artists/hieuthuhai/audio/23 - NOLOVENOLIFE.mp3": ``,
  "assets/artists/hieuthuhai/audio/3 - Nước Mắt Cá Sấu.mp3": ``,
  "assets/artists/hieuthuhai/audio/4 - Người Im Lặng Gặp Người Hay Nói.mp3": ``,
  "assets/artists/hieuthuhai/audio/5 - Sắp Nổi Tiếng 2.mp3": ``,
  "assets/artists/hieuthuhai/audio/6 - Vacheron Louie V ft Hustlang Robber.mp3": ``,
  "assets/artists/hieuthuhai/audio/7 - Đáng Lý Anh Nên Yêu Em Hơn ft HURRYKNG.mp3": ``,
  "assets/artists/hieuthuhai/audio/8 - Đâu Có Ai Nhìn.mp3": ``,
  "assets/artists/hieuthuhai/audio/9 - Đâu Cần Gì Hơn.mp3": ``,
  "assets/artists/hustlangrobber/audio/1 - 1TINHYEU ft Young Puppy.mp3": ``,
  "assets/artists/hustlangrobber/audio/10 - QUA TỪNG KHUNG HÌNH ft Ngắn.mp3": ``,
  "assets/artists/hustlangrobber/audio/11 - Rapper Lè Nhè.mp3": ``,
  "assets/artists/hustlangrobber/audio/12 - Slatt ON.mp3": ``,
  "assets/artists/hustlangrobber/audio/13 - Take It Off.mp3": ``,
  "assets/artists/hustlangrobber/audio/14 - Xuôi Chèo Mát Mái.mp3": ``,
  "assets/artists/hustlangrobber/audio/2 - Cartier Rings.mp3": ``,
  "assets/artists/hustlangrobber/audio/3 - Có Nhiều Đêm Anh Buồn.mp3": ``,
  "assets/artists/hustlangrobber/audio/4 - Dear Love.mp3": ``,
  "assets/artists/hustlangrobber/audio/5 - His Story.mp3": ``,
  "assets/artists/hustlangrobber/audio/6 - IKIGAI.mp3": ``,
  "assets/artists/hustlangrobber/audio/7 - King Vamp.mp3": ``,
  "assets/artists/hustlangrobber/audio/8 - Muốn Anh Đau ft WINNO.mp3": ``,
  "assets/artists/hustlangrobber/audio/9 - MỘT TÂM HỒN BÌNH THẢN.mp3": ``,
  "assets/artists/mck/audio/1 - Elegie.mp3": ``,
  "assets/artists/mck/audio/10 - Night In Prague.mp3": ``,
  "assets/artists/mck/audio/11 - Một Cái Ôm.mp3": ``,
  "assets/artists/mck/audio/12 - Liệm.mp3": ``,
  "assets/artists/mck/audio/13 - Nếu Như Ta Chẳng Còn ft A$AP Ướt Mi.mp3": ``,
  "assets/artists/mck/audio/14 - Ai Mới Là Kẻ Xấu Xa.mp3": ``,
  "assets/artists/mck/audio/15 - Slippery ft Tùng Dương.mp3": ``,
  "assets/artists/mck/audio/16 - Intenpol.mp3": ``,
  "assets/artists/mck/audio/17 - Tây thi.mp3": ``,
  "assets/artists/mck/audio/18 - Hút và Hút.mp3": ``,
  "assets/artists/mck/audio/19 - Dưa chua.mp3": ``,
  "assets/artists/mck/audio/2 - IDK.mp3": ``,
  "assets/artists/mck/audio/20 - Xa xôi ft Obito.mp3": ``,
  "assets/artists/mck/audio/21 - Che Phủ.mp3": ``,
  "assets/artists/mck/audio/22 - Oanh M = Thuoc.mp3": ``,
  "assets/artists/mck/audio/23 - Ghet Xog Lai Thik.mp3": ``,
  "assets/artists/mck/audio/24 - Nhìn Kẻ Thù Của Tao.mp3": ``,
  "assets/artists/mck/audio/25 - Envy.mp3": ``,
  "assets/artists/mck/audio/26 - Cảm Ơn.mp3": ``,
  "assets/artists/mck/audio/27 - Không Cần Lo Cho Tao.mp3": ``,
  "assets/artists/mck/audio/28 - Huh ft RPT Orijinn & Thanh Draw.mp3": ``,
  "assets/artists/mck/audio/29 - Nguyễn Văn Mười.mp3": ``,
  "assets/artists/mck/audio/3 - Wtf Bby I’m Lit.mp3": ``,
  "assets/artists/mck/audio/30 - Thịt Lợn.mp3": ``,
  "assets/artists/mck/audio/31 - N0L4B3L ft Thành Draw, RPT Orijinn.mp3": ``,
  "assets/artists/mck/audio/4 - Anh Không Muốn Nó Dễ Dàng.mp3": ``,
  "assets/artists/mck/audio/5 - Baby ft Marzuz.mp3": ``,
  "assets/artists/mck/audio/6 - Yêu Anh Giết Anh.mp3": ``,
  "assets/artists/mck/audio/7 - Mắt Môi Tay Chân ft Tage.mp3": ``,
  "assets/artists/mck/audio/8 - Đao Của Anh Vừa.mp3": ``,
  "assets/artists/mck/audio/9 - Là Gì Của Nhau.mp3": ``,
  "assets/artists/obito/audio/1 - Xuất Phát Điểm.mp3": ``,
  "assets/artists/obito/audio/10 - Simple Love.mp3": ``,
  "assets/artists/obito/audio/11 - Soju Love.mp3": ``,
  "assets/artists/obito/audio/12 - Sài Gòn ơi.mp3": ``,
  "assets/artists/obito/audio/13 - Track 06.mp3": ``,
  "assets/artists/obito/audio/14 - When You Look At Me.mp3": ``,
  "assets/artists/obito/audio/15 - dư âm.mp3": ``,
  "assets/artists/obito/audio/16 - nước.mp3": ``,
  "assets/artists/obito/audio/17 - Đánh Đổi.mp3": ``,
  "assets/artists/obito/audio/2 - 1000 Ánh Mắt.mp3": ``,
  "assets/artists/obito/audio/3 - Đầu Đường Xó Chợ ft. Lăng LD.mp3": ``,
  "assets/artists/obito/audio/4 - Biên Giới Long Bình.mp3": ``,
  "assets/artists/obito/audio/5 - BUSINESS MODE.mp3": ``,
  "assets/artists/obito/audio/6 - Lost.mp3": ``,
  "assets/artists/obito/audio/7 - Panorama.mp3": ``,
  "assets/artists/obito/audio/8 - Phong Long.mp3": ``,
  "assets/artists/obito/audio/9 - Shay Nắnggg.mp3": ``,
  "assets/artists/tinhhasayhi/audio/1 - THẾ GIỚI CỦA ANH ft Dương Domic & buitruonglinh & CONGB & WEAN & Vận Toàn.mp3": ``,
  "assets/artists/tinhhasayhi/audio/10 - SECRET ft Quang Hùng MasterD & Cody Nam Võ & CongB & Wren Evans.mp3": ``,
  "assets/artists/tinhhasayhi/audio/11 - MỘNG DUYÊN ft Quang Hùng MasterD & JSOL & Sơn.K & Song Luân & EMIL VERGO.mp3": ``,
  "assets/artists/tinhhasayhi/audio/2 - CÔ ĐƠN ANH CŨNG VUI ft WEAN & DILLAN & KIMLONG & Xuân Định KY.mp3": ``,
  "assets/artists/tinhhasayhi/audio/3 - CÓ GÌ ĐÂU MÀ CAY ft CAPTAIN BOY & CoolKid & IVAN & XUÂN ĐỊNH KY & LEONSASH.mp3": ``,
  "assets/artists/tinhhasayhi/audio/4 - MẤT LA BÀN ft Pháp Kiều & Thể Thiên & VƯƠNG BÌNH & DANG HONG HAI & TORYSAX.mp3": ``,
  "assets/artists/tinhhasayhi/audio/5 - MƯA VỘI PHÓNG ft Wren Evans & Ali Hoàng Dương & Cody Nam Võ & HYO & 2PILLZ.mp3": ``,
  "assets/artists/tinhhasayhi/audio/6 - 50 CUỘC GỌI NHỠ ft CoolKid & Quang Hùng MasterD & Cody Nam Võ & Jaysonlei.mp3": ``,
  "assets/artists/tinhhasayhi/audio/7 - IM ĐỢI NGƯỜI ANH THƯƠNG ft Wren Evans & CAPTAIN BOY & IVAN & Thể Thiên.mp3": ``,
  "assets/artists/tinhhasayhi/audio/8 - XOAY VÒNG ft HURRYKNG & JSOL & VƯƠNG BÌNH & CONGB.mp3": ``,
  "assets/artists/tinhhasayhi/audio/9 - MRT ft XUÂN ĐỊNH KY & buitruonglinh & CAPTAIN BOY & HYO.mp3": ``,
  "assets/artists/wrenevans/audio/1 - Từng Quen.mp3": ``,
  "assets/artists/wrenevans/audio/10 - Cứu Lấy Âm Nhạc.mp3": ``,
  "assets/artists/wrenevans/audio/11 - Phóng Đổ Tim Em.mp3": ``,
  "assets/artists/wrenevans/audio/12 - ĐĐĐ.mp3": ``,
  "assets/artists/wrenevans/audio/13 - Để Ý.mp3": ``,
  "assets/artists/wrenevans/audio/14 - Cầu Vĩnh Tuy.mp3": ``,
  "assets/artists/wrenevans/audio/15 - mưa chưa tạnh (interlude).mp3": ``,
  "assets/artists/wrenevans/audio/16 - Thu Đợi.mp3": ``,
  "assets/artists/wrenevans/audio/2 - Tình Yêu Vĩ Mô.mp3": ``,
  "assets/artists/wrenevans/audio/3 - Quyền Anh.mp3": ``,
  "assets/artists/wrenevans/audio/4 - Lối Chơi (Interlude).mp3": ``,
  "assets/artists/wrenevans/audio/5 - Tò Te Tí.mp3": ``,
  "assets/artists/wrenevans/audio/6 - Vừa Tìm Thấy Đã Đánh Mất.mp3": ``,
  "assets/artists/wrenevans/audio/7 - Gió Đưa Tình.mp3": ``,
  "assets/artists/wrenevans/audio/8 - bé ơi từ từ.mp3": ``,
  "assets/artists/wrenevans/audio/9 - Call Me.mp3": ``,
  "assets/artists/wxrdie/audio/1 - 29.mp3": ``,
  "assets/artists/wxrdie/audio/10 - Lâu Đài.mp3": ``,
  "assets/artists/wxrdie/audio/11 - Lối Sống.mp3": ``,
  "assets/artists/wxrdie/audio/12 - Mời Em.mp3": ``,
  "assets/artists/wxrdie/audio/13 - Nu Cep.mp3": ``,
  "assets/artists/wxrdie/audio/14 - Pray For.mp3": ``,
  "assets/artists/wxrdie/audio/15 - Thèn Chóa.mp3": ``,
  "assets/artists/wxrdie/audio/16 - Thíc Qé.mp3": ``,
  "assets/artists/wxrdie/audio/17 - Tim Anh Ghen.mp3": ``,
  "assets/artists/wxrdie/audio/18 - Trở Về.mp3": ``,
  "assets/artists/wxrdie/audio/19 - Đau Đầu.mp3": ``,
  "assets/artists/wxrdie/audio/2 - Anh Freestyle.mp3": ``,
  "assets/artists/wxrdie/audio/3 - Băng Qua Cầu Giấy.mp3": ``,
  "assets/artists/wxrdie/audio/4 - Bởi Vì.mp3": ``,
  "assets/artists/wxrdie/audio/5 - Ca Khúc Cuối.mp3": ``,
  "assets/artists/wxrdie/audio/6 - Cả 2.mp3": ``,
  "assets/artists/wxrdie/audio/7 - Get Money.mp3": ``,
  "assets/artists/wxrdie/audio/8 - Gia Tài.mp3": ``,
  "assets/artists/wxrdie/audio/9 - Lonely Stonie.mp3": ``
};
